//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rzut.Interface.Data.i18n.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_pirate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_pirate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rzut.Interface.Data.i18n.Resources.Strings.pirate", typeof(Strings_pirate).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotatin&apos; velocity arrr.
        /// </summary>
        internal static string Body_AngularVelocity {
            get {
                return ResourceManager.GetString("Body_AngularVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight velocity arrr.
        /// </summary>
        internal static string Body_LinearVelocity {
            get {
                return ResourceManager.GetString("Body_LinearVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wher&apos; standin&apos; ya.
        /// </summary>
        internal static string Body_Position {
            get {
                return ResourceManager.GetString("Body_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How fa&apos; the ball can g&apos;.
        /// </summary>
        internal static string Body_Range {
            get {
                return ResourceManager.GetString("Body_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New flesh.
        /// </summary>
        internal static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARRR.
        /// </summary>
        internal static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon ship.
        /// </summary>
        internal static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loa&apos; th gunz.
        /// </summary>
        internal static string Checkbox_EnableCollisions {
            get {
                return ResourceManager.GetString("Checkbox_EnableCollisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sh*t to sh*t [px/m].
        /// </summary>
        internal static string Config_UnitRatio {
            get {
                return ResourceManager.GetString("Config_UnitRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stench density [kg/m^3].
        /// </summary>
        internal static string EntityViewModel_AirDensity {
            get {
                return ResourceManager.GetString("EntityViewModel_AirDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind in ya ungly face.
        /// </summary>
        internal static string EntityViewModel_AirResistance {
            get {
                return ResourceManager.GetString("EntityViewModel_AirResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotatin&apos; harpin.
        /// </summary>
        internal static string EntityViewModel_AngularDrag {
            get {
                return ResourceManager.GetString("EntityViewModel_AngularDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotatin&apos; velocity [rad/s].
        /// </summary>
        internal static string EntityViewModel_AngularVelocity {
            get {
                return ResourceManager.GetString("EntityViewModel_AngularVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harpin.
        /// </summary>
        internal static string EntityViewModel_Friction {
            get {
                return ResourceManager.GetString("EntityViewModel_Friction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration [m/s^2].
        /// </summary>
        internal static string EntityViewModel_GravitationalAcceleration {
            get {
                return ResourceManager.GetString("EntityViewModel_GravitationalAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass [kg].
        /// </summary>
        internal static string EntityViewModel_Mass {
            get {
                return ResourceManager.GetString("EntityViewModel_Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius [m].
        /// </summary>
        internal static string EntityViewModel_Radius {
            get {
                return ResourceManager.GetString("EntityViewModel_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restitution.
        /// </summary>
        internal static string EntityViewModel_Restitution {
            get {
                return ResourceManager.GetString("EntityViewModel_Restitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise angle [degrees].
        /// </summary>
        internal static string EntityViewModel_StartAngle {
            get {
                return ResourceManager.GetString("EntityViewModel_StartAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-coordinate [m].
        /// </summary>
        internal static string EntityViewModel_StartX {
            get {
                return ResourceManager.GetString("EntityViewModel_StartX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-coordinate [m].
        /// </summary>
        internal static string EntityViewModel_StartY {
            get {
                return ResourceManager.GetString("EntityViewModel_StartY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity [m/s].
        /// </summary>
        internal static string EntityViewModel_Velocity {
            get {
                return ResourceManager.GetString("EntityViewModel_Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string Header_ChooseLanguage {
            get {
                return ResourceManager.GetString("Header_ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficients.
        /// </summary>
        internal static string Header_Coefficients {
            get {
                return ResourceManager.GetString("Header_Coefficients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Header_Color {
            get {
                return ResourceManager.GetString("Header_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw parameters.
        /// </summary>
        internal static string Header_ThrowParameters {
            get {
                return ResourceManager.GetString("Header_ThrowParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ball throw simulator.
        /// </summary>
        internal static string Header_Title {
            get {
                return ResourceManager.GetString("Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        internal static string Header_World {
            get {
                return ResourceManager.GetString("Header_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} rad/s.
        /// </summary>
        internal static string Overlay_AngularVelocity {
            get {
                return ResourceManager.GetString("Overlay_AngularVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Overlay_Back {
            get {
                return ResourceManager.GetString("Overlay_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Overlay_Distance {
            get {
                return ResourceManager.GetString("Overlay_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:00} m/s.
        /// </summary>
        internal static string Overlay_LinearVelocity {
            get {
                return ResourceManager.GetString("Overlay_LinearVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: {0:0.00} m/s | Y: {1:0.00} m/s.
        /// </summary>
        internal static string Overlay_LinearVelocityDetails {
            get {
                return ResourceManager.GetString("Overlay_LinearVelocityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: {0:0.00} m | Y: {1:0.00} m.
        /// </summary>
        internal static string Overlay_Position {
            get {
                return ResourceManager.GetString("Overlay_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} m.
        /// </summary>
        internal static string Overlay_Range {
            get {
                return ResourceManager.GetString("Overlay_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ball {0}.
        /// </summary>
        internal static string Tab_Ball {
            get {
                return ResourceManager.GetString("Tab_Ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1:0.00} and {2:0.00}.
        /// </summary>
        internal static string Validation_Range_float {
            get {
                return ResourceManager.GetString("Validation_Range_float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1:N0} and  {2:N0}.
        /// </summary>
        internal static string Validation_Range_int {
            get {
                return ResourceManager.GetString("Validation_Range_int", resourceCulture);
            }
        }
    }
}
